export const MUSICIANS = [
    {
        id: 0,
        name: "Bob Dylan",
        birthDate: "May 24, 1941",
        birthPlace: "Duluth, Minnesota, United States",
        sunSign: "Gemini",
        bio: "Singer-songwriter and author, Bob Dylan, is widely regarded as one of the greatest songwriters of all time. Active in the music industry for almost six decades, he is a major pop culture icon who introduced a range of political, social, and literary influences to pop music. He is a Nobel laureate and a recipient of the Presidential Medal of Freedom.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/bob-dylan-2.jpg",
    },
    {
        id: 1,
        name: "Jim Morrison",
        birthDate: "December 8, 1943",
        birthPlace: "Melbourne, Florida, United States",
        sunSign: "Sagittarius",
        bio: "Considered the prototypical rock star, Jim Morrison remains one of the most influential singer-songwriters, almost five decades after his death. Jim influenced the counterculture of the 1960s as he embodied the hippie counterculture rebellion. Due to his erratic performances and wild personality, he is regarded as one of the most iconic frontmen in rock history.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/jim-morrison-18.jpg",
    },
    {
        id: 2,
        name: "Prince",
        birthDate: "June 7, 1958",
        birthPlace: "Minneapolis, Minnesota, United States",
        sunSign: "Gemini",
        bio: "Singer-songwriter, dancer, and musician, Prince is is widely regarded as one of the greatest musicians of his generation. He was considered a guitar virtuoso and could also play several other instruments. With worldwide sales of over 150 million records, he is ranked among the best-selling music artists of all time. He was also well known for his flamboyant persona.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/prince-3.jpg",
    },
    {
        id: 3,
        name: "Johnny Cash",
        birthDate: "February 26, 1932",
        birthPlace: "Kingsland, Arkansas, United States",
        sunSign: "Pisces",
        bio: "Johnny Cash, the American singer, songwriter and actor, was known for sorrow, moral suffering and redemption themes in his music. His genre was country, rock and roll, blues, folk and gospel sounds and he is one of the best-selling artists of all time. Cash had issues with drinking and drug abuse. Later he was diagnosed with a neurodegenerative disease.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/johnny-cash-5.jpg",
    },
    {
        id: 4,
        name: "Dolly Parton",
        birthDate: "January 19, 1946",
        birthPlace: "Locust Ridge, Tennessee, United States",
        sunSign: "Capricorn",
        bio: "Multifaceted personality, Dolly Parton is a singer, songwriter, record producer, actress, author and businesswoman and is known mainly for her work in country music. She has received various accolades and awards in her very successful singing career spanning several decades and has composed over 3,000 songs. She has also worked in several movies and is a prolific songwriter.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/dolly-parton-6.jpg",
    },
    {
        id: 5,
        name: "Axl Rose",
        birthDate: "February 6, 1962",
        birthPlace: "Lafayette, Indiana, United States",
        sunSign: "Aquarius",
        bio: "Rock and Roll Hall of Famer W. Axl Rose, being true to his rebel spirit, fled to Los Angeles on a bus at 17, before he co-founded the legendary hard rock band Guns N' Roses. Working as the lead vocalist/lyricist of the band, he soon became a global sex symbol.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/axl-rose-3.jpg",
    },
];
