export const SINGERS = [
    {
        id: 0,
        name: "Michael Jackson",
        birthDate: "August 29, 1958",
        birthPlace: "Gary, Indiana",
        sunSign: "Virgo",
        bio: "The King of Pop and an international superstar, Michael Jackson was a musical entertainer whose work – both with Jackson 5 and solo – won accolades and hearts worldwide. Equally popular were his unique dance moves that created sensation and shaped future dance styles. Amongst the most successful entertainers of all time, Jackson was later accused of child molestation.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/michael-jackson-4.jpg",
    },
    {
        id: 1,
        name: "Elvis Presley",
        birthDate: "January 8, 1935",
        birthPlace: "Tupelo, Mississippi, United States",
        sunSign: "Capricorn",
        bio: "The King of Rock ‘n’ Roll, winner of 3 Grammys, and pioneer of the Pelvis move, Elvis Presley was a musical phenomenon of the 20th century. Known for his humbleness, love for God and devotion to his country, Presley had numerous gold, platinum and multi-platinum records to his credit, including 18 number 1 hits and 38 top ten hits.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/elvis-presley-7.jpg",
    },
    {
        id: 2,
        name: "Kenny Rogers",
        birthDate: "August 21, 1938",
        birthPlace: "Houston",
        sunSign: "Leo",
        bio: "Kenny Rogers was an American singer-songwriter. He is among the best-selling musicians of all-time list, having sold over 100 million records. His songs and albums remain influential among country music lovers. A multi-talented personality, Rogers was also successful as an actor and entrepreneur; he was the co-founder of the Kenny Rogers Roasters chain of restaurants.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/kenny-rogers-2.jpg",
    },
    {
        id: 3,
        name: "Glen Campbell",
        birthDate: "April 22, 1936",
        birthPlace: "Billstown, Arkansas",
        sunSign: "Taurus",
        bio: "Glen Campbell was an American TV host, actor, singer-songwriter, and guitarist. Regarded as one of the most successful musicians ever, Campbell sold more than 45 million records, which included a double-platinum album, four platinum albums, and 12 gold albums, in a career spanning 50 years. In 2014, he became the subject of a documentary titled Glen Campbell: I'll Be Me.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/glen-campbell-1.jpg",
    },
    {
        id: 4,
        name: "Jon Bon Jovi",
        birthDate: "March 2, 1962",
        birthPlace: "Perth Amboy, New Jersey, United States",
        sunSign: "Pisces",
        bio: "Known as the iconic founder of the popular rock band Bon Jovi, Jon Bon Jovi is a record producer and singer-songwriter. In 2012, he was named in Billboard magazine's The Most Powerful and Influential People In The Music Business list. Also a well-known philanthropist, he founded the Jon Bon Jovi Soul Foundation in an attempt to eradicate poverty and homelessness.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/jon-bon-jovi-3.jpg",
    },
    {
        id: 5,
        name: "Jerry Lee Lewis",
        birthDate: "September 29, 1935",
        birthPlace: "Ferriday, Louisiana, United States",
        sunSign: "Libra",
        bio: "Four-time Grammy-winner Jerry Lee Lewis, nicknamed “The Killer,” is best known for his track Great Balls of Fire. A controversy surrounding his marriage to his 13-year-old cousin Myra destroyed his career. Named to Rolling Stone’s 100 Greatest Artists of All Time, he was also part of the Million Dollar Quartet.",
        image: "https://www.thefamouspeople.com/profiles/thumbs/jerry-lee-lewis-1.jpg",
    },
];
